AWSTemplateFormatVersion: 2010-09-09
Description: 'CloudFormation Skeleton'
Metadata:
  Instances:
    Description: "The Metadata block is entirely optional."
Parameters: 
  InstanceTypeParameter: 
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.micro
      - m5.large
    Description: Enter t2.micro or m5.large. Default is t2.micro.
Mappings: 
  RegionMap: 
    us-east-1: 
      "HVM64": ""
    eu-west-1: 
      "HVM64": ""
    ap-southeast-1: 
      "HVM64": ""
#Conditions: 
Resources: 
  EC2Instance: 
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", HVM64]
      InstanceType: !Ref InstanceTypeParameter

Outputs:
  InstanceID:
    Description: "The Instance ID"
    Value: !Ref EC2Instance