name: Build documentation

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Build the prerequisites
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material
    - name: Build the documentation
      run: mkdocs build
    - name: Deploy Github Pages
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./site
